databases:
  - name: stocktrack
    plan: free
    databaseName: stocktrack
    user: stocktrack
    region: singapore

services:
  - type: web
    plan: free
    name: stocktrack
    runtime: python
    region: singapore
    buildCommand: "./build.sh"
    startCommand: "python -m gunicorn asset_backend.asgi:application -k uvicorn.workers.UvicornWorker"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: stocktrack
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4