# Generated by Django 5.0.3 on 2024-03-17 13:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cashes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CashTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('money', models.PositiveIntegerField(default=0)),
                ('date', models.DateField(null=True)),
                ('cash_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cashes.cash')),
            ],
        ),
    ]
