# Generated by Django 5.0.3 on 2024-04-01 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cashes', '0002_cashtransaction'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cash',
            name='money',
        ),
    ]
