# Generated by Django 5.0.3 on 2024-04-01 13:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cashes', '0003_remove_cash_money'),
        ('categories', '0004_alter_categorytransaction_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cash',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cash', to='categories.category'),
        ),
    ]
