# Generated by Django 5.0.3 on 2024-04-01 13:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cashes', '0004_alter_cash_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cashtransaction',
            name='cash_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transaction', to='cashes.cash'),
        ),
    ]
