# Generated by Django 5.0.3 on 2024-03-17 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0002_categorytransaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='categorytransaction',
            name='asset',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='categorytransaction',
            name='date',
            field=models.DateField(null=True),
        ),
    ]
