# Generated by Django 5.0.3 on 2024-03-17 21:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0003_categorytransaction_asset_categorytransaction_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorytransaction',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transaction', to='categories.category'),
        ),
    ]
