# Generated by Django 5.0.3 on 2024-05-28 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0005_categorytransaction_realize_money_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='classification',
            field=models.CharField(choices=[('stock', '주식'), ('bank', '예금')], default='stock', max_length=10),
        ),
    ]
