# Generated by Django 5.0.3 on 2024-05-29 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0007_categorytotal'),
    ]

    operations = [
        migrations.AddField(
            model_name='categorytotal',
            name='date',
            field=models.DateField(null=True),
        ),
    ]
