# Generated by Django 5.0.3 on 2024-06-03 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0008_categorytotal_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='categorytransaction',
            old_name='asset',
            new_name='total_asset',
        ),
        migrations.AddField(
            model_name='categorytransaction',
            name='asset_krw',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='categorytransaction',
            name='asset_usd',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='categorytransaction',
            name='usd_rate',
            field=models.FloatField(default=0),
        ),
    ]
