# Generated by Django 5.0.3 on 2024-03-30 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0003_alter_stock_category_alter_stocktransaction_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='stocktransaction',
            name='total_amount',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='stocktransaction',
            name='total_average_price',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='stocktransaction',
            name='total_stock_asset',
            field=models.FloatField(default=0),
        ),
    ]
