# Generated by Django 5.0.3 on 2024-03-31 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0005_stocktransaction_market_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stocktransaction',
            name='price',
            field=models.FloatField(default=0),
        ),
    ]
