# Generated by Django 5.0.3 on 2024-04-07 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0006_alter_stocktransaction_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='stocktransaction',
            name='realize_money',
            field=models.FloatField(default=0),
        ),
    ]
